packages:
  - 'apps/*'

catalog:
  'vite': '6.1.0'
catalogs:
  svelte:
    '@sveltejs/adapter-node': '5.2.12'
    '@sveltejs/kit': '2.17.2'
    '@sveltejs/vite-plugin-svelte': '5.0.3'
    'svelte': '5.20.1'
    'svelte-check': '4.1.4'
  tailwindcss:
    'tailwindcss': '4.0.6'
    '@tailwindcss/vite': '4.0.6'
