# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "swag init -g ./cmd/main.go && go build -o ./tmp/main ./cmd/."
  bin = "./tmp/main"
  delay = 1000 # ms
  exclude_dir = [".turbo", "assets", "tmp", "vendor", "docs"]

[run]
  cmd = "./tmp/main"

[log]
  time = false
  log_format = "air {{time .}} | {{title .Level}} | {{message .}}"

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[misc]
  clean_on_exit = true