# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go run main.go"
  bin = "./tmp/main"
  delay = 1000 # ms
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]

[log]
  time = false
  log_format = "air {{time .}} | {{title .Level}} | {{message .}}"

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[misc]
  clean_on_exit = true

# .gitignore (append this)
/tmp
.air.toml

# Makefile
dev:
    air